# Generated by Django 3.1 on 2024-11-11 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_delete_post'),
        ('post', '0005_auto_20220208_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='group.group'),
            preserve_default=False,
        ),
    ]
