# Generated by Django 5.1.2 on 2024-11-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_post_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
