# Generated by Django 3.1 on 2024-11-11 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20241111_1356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
