# Generated by Django 5.1.2 on 2024-11-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_page_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='Nội dung mặc định'),
        ),
    ]
