# Generated by Django 3.1 on 2024-11-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0007_alter_blockeduser_id_alter_friend_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockeduser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
