# Generated by Django 5.1.2 on 2024-11-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0010_auto_20241114_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blockeduser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
