# Generated by Django 5.1.2 on 2024-11-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directs', '0004_message_image_alter_message_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture/'),
        ),
    ]
