# Generated by Django 5.1.2 on 2024-11-23 16:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directs', '0009_message_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='conversation_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
