# Generated by Django 5.1.2 on 2024-11-24 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("directs", "0010_message_conversation_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="likes",
        ),
    ]
