# Generated by Django 5.1.2 on 2024-10-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0007_alter_profile_image_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blocked_friends',
            field=models.ManyToManyField(blank=True, related_name='blocked_by', to='authy.profile'),
        ),
    ]
