# Generated by Django 5.1.2 on 2024-11-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authy", "0009_profile_is_private"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="cover_photo",
            field=models.ImageField(
                default="default_cover.jpg", upload_to="cover_photos/"
            ),
        ),
    ]
